# Generated by Django 2.0 on 2018-01-31 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180112_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file_type',
            new_name='audio_file',
        ),
    ]
